export const lightTheme = {
  primary: "#6c63ff",
  secondary: "#F4F4FB",
  accent: "#38A2FF",
  background: "#FFFFFF",
  text: "#000000",
  textSecondary: "#666666",
  cardBackground: "#F4F4FB",
  illustrationPrimary: "#6c63ff",
  illustrationSecondary: "#000000",
  dotInactive: "#E0E0E0",
  nextButtonBackground: "#F5F5F5",
  nextButtonInner: "#000000",
  nextButtonText: "#FFFFFF",
  // Dashboard specific colors
  white: "#FFFFFF",
  success: "#4CAF50",
  card: "#FFFFFF",
  border: "#E0E0E0",
  shadow: "rgba(0, 0, 0, 0.1)",
  // CreateExpenseBoard specific colors
  error: "#FF6B6B",
  sectionBackground: "#FFFFFF",
  sectionBorder: "rgba(0, 0, 0, 0.1)",
  inputBackground: "#FFFFFF",
  inputBorder: "#E0E0E0",
  selectedColorBorder: "#FFFFFF",
  iconBackground: "#FFFFFF",
  iconSelectedBackground: "rgba(108, 99, 255, 0.1)", // 20% opacity of primary color
};

export const darkTheme = {
  primary: "#6c63ff",
  secondary: "#2A2A2A",
  accent: "#38A2FF",
  background: "#121212",
  text: "#FFFFFF",
  textSecondary: "#AAAAAA",
  cardBackground: "#2A2A2A",
  illustrationPrimary: "#6c63ff",
  illustrationSecondary: "#FFFFFF",
  dotInactive: "#333333",
  nextButtonBackground: "#333333",
  nextButtonInner: "#FFFFFF",
  nextButtonText: "#000000",
  // Dashboard specific colors
  white: "#FFFFFF",
  success: "#4CAF50",
  card: "#2A2A2A",
  border: "#333333",
  shadow: "rgba(0, 0, 0, 0.3)",
  // CreateExpenseBoard specific colors
  error: "#FF6B6B",
  sectionBackground: "#2A2A2A",
  sectionBorder: "rgba(255, 255, 255, 0.1)",
  inputBackground: "#2A2A2A",
  inputBorder: "#333333",
  selectedColorBorder: "#FFFFFF",
  iconBackground: "#2A2A2A",
  iconSelectedBackground: "rgba(108, 99, 255, 0.2)", // 20% opacity of primary color
};
