/** ISO 3166-1 alpha-2 country code → ISO 4217 currency code */
export const COUNTRY_TO_CURRENCY = {
  IN: "INR",
  US: "USD",
  GB: "GBP",
  AU: "AUD",
  CA: "CAD",
  SG: "SGD",
  NZ: "NZD",
  HK: "HKD",
  CH: "CHF",
  NO: "NOK",
  SE: "SEK",
  DK: "DKK",
  JP: "JPY",
  KR: "KRW",
  TW: "TWD",
  AE: "AED",
  IL: "ILS",
  SA: "SAR",
  QA: "QAR",
  KW: "KWD",
  BH: "BHD",
  OM: "OMR",
  FI: "EUR",
  IE: "EUR",
  NL: "EUR",
  BE: "EUR",
  AT: "EUR",
  DE: "EUR",
  FR: "EUR",
  IT: "EUR",
  ES: "EUR",
  PT: "EUR",
  LU: "EUR",
  IS: "EUR",
  MC: "EUR",
  AD: "EUR",
  CY: "EUR",
  MT: "EUR",
  SI: "EUR",
  LI: "CHF",
  MX: "MXN",
  BR: "BRL",
  ZA: "ZAR",
  TH: "THB",
  MY: "MYR",
  ID: "IDR",
  PH: "PHP",
  VN: "VND",
  CN: "CNY",
  PK: "PKR",
  BD: "BDT",
  LK: "LKR",
  NP: "NPR",
};

export const DEFAULT_CURRENCY = "USD";

export function currencyForCountry(countryCode) {
  if (!countryCode) return null;
  return COUNTRY_TO_CURRENCY[String(countryCode).toUpperCase()] ?? null;
}
